FROM gocd/gocd-agent-alpine-3.5:v17.4.0

ENV BUILD_PACKAGES bash curl-dev ruby-dev build-base
ENV NPM_PACKAGES nodejs
ENV JAVA_PACKAGES openjdk8

# Update and install all of the required packages.
# At the end, remove the apk cache
RUN apk update && \
    apk upgrade && \
    apk add $BUILD_PACKAGES && \
    apk add $NPM_PACKAGES && \
    apk add $JAVA_PACKAGES && \
    rm -rf /var/cache/apk/*
