FROM gocd/gocd-agent-ubuntu-16.04:v17.12.0

ENV CORE_PACKAGES bash build-essential

# Update and install all of the required packages
RUN apt-get update -yqq \
    && apt-get install -yqq \
      $CORE_PACKAGES \
    && apt-get update -yqq \
    && apt-get clean \
    && rm -rf \
        /var/lib/apt/lists/* \
        /tmp/* \
        /var/tmp/* \
        /usr/share/man \
        /usr/share/doc \
        /usr/share/doc-base

# Install Docker and docker-compose
ENV DOCKER_PACKAGES apt-transport-https ca-certificates curl software-properties-common
RUN apt-get update -yqq \
    && apt-get install -yqq \
      $DOCKER_PACKAGES \
    && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    && curl -fsSL https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose \
    && apt-get update -yqq \
    && apt-get install -yqq docker-ce \
    && apt-get clean \
    && rm -rf \
        /var/lib/apt/lists/* \
        /tmp/* \
        /var/tmp/* \
        /usr/share/man \
        /usr/share/doc \
        /usr/share/doc-base

# Add go user to root group to properly use the docker.sock
RUN gpasswd -a go root

# Add github to known_hosts
RUN mkdir -p /home/go/.ssh
RUN ssh-keyscan -t rsa github.com >> /home/go/.ssh/known_hosts

# Add private key to access github repositories
ARG PRIVATE_KEY
RUN echo "${PRIVATE_KEY}" >> /home/go/.ssh/id_rsa
RUN chown -R 1000:1000 /home/go/.ssh
RUN chmod 400 /home/go/.ssh/id_rsa