pipelines:
  MovieSurfer:
    group: applications
    materials:
      mygit:
        git: https://github.com/sebradloff/movie-surfer.git
    stages:
      - Build:
          clean_workspace: true
          jobs:
            Build:
              tasks:
                - script: docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
                - script: docker build -t $DOCKER_USERNAME/movie-surfer-snap .
                - script: docker push $DOCKER_USERNAME/movie-surfer-snap
      - UnitTest:
          jobs:
            UnitTest:
              tasks:
                - script: docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
                - script: docker pull $DOCKER_USERNAME/movie-surfer-snap
                - script: docker run --rm --entrypoint npm $DOCKER_USERNAME/movie-surfer-snap test
      - Publish:
          jobs:
            Publish:
              tasks:
                - script: docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
                - script: docker pull $DOCKER_USERNAME/movie-surfer-snap
                - script: docker tag $DOCKER_USERNAME/movie-surfer-snap $DOCKER_USERNAME/movie-surfer
                - script: docker push $DOCKER_USERNAME/movie-surfer
